/*******************************************************************************
* File Name: cyfitter_gpio.h
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_GPIO_H
#define INCLUDED_CYFITTER_GPIO_H
#include "cy_device_headers.h"

/* Pin_LED3 */
#define Pin_LED3_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Pin_LED3_0_INBUF_ENABLED 0u
#define Pin_LED3_0_INIT_DRIVESTATE 1u
#define Pin_LED3_0_INIT_MUXSEL 0u
#define Pin_LED3_0_INPUT_SYNC 2u
#define Pin_LED3_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Pin_LED3_0_NUM 3u
#define Pin_LED3_0_PORT GPIO_PRT6
#define Pin_LED3_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Pin_LED3_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Pin_LED3_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Pin_LED3_INBUF_ENABLED 0u
#define Pin_LED3_INIT_DRIVESTATE 1u
#define Pin_LED3_INIT_MUXSEL 0u
#define Pin_LED3_INPUT_SYNC 2u
#define Pin_LED3_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Pin_LED3_NUM 3u
#define Pin_LED3_PORT GPIO_PRT6
#define Pin_LED3_SLEWRATE CY_GPIO_SLEW_FAST
#define Pin_LED3_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* Pin_LED4 */
#define Pin_LED4_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Pin_LED4_0_INBUF_ENABLED 0u
#define Pin_LED4_0_INIT_DRIVESTATE 1u
#define Pin_LED4_0_INIT_MUXSEL 0u
#define Pin_LED4_0_INPUT_SYNC 2u
#define Pin_LED4_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Pin_LED4_0_NUM 1u
#define Pin_LED4_0_PORT GPIO_PRT7
#define Pin_LED4_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Pin_LED4_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Pin_LED4_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Pin_LED4_INBUF_ENABLED 0u
#define Pin_LED4_INIT_DRIVESTATE 1u
#define Pin_LED4_INIT_MUXSEL 0u
#define Pin_LED4_INPUT_SYNC 2u
#define Pin_LED4_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Pin_LED4_NUM 1u
#define Pin_LED4_PORT GPIO_PRT7
#define Pin_LED4_SLEWRATE CY_GPIO_SLEW_FAST
#define Pin_LED4_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

#endif /* INCLUDED_CYFITTER_GPIO_H */
